import json
import os

from lunar.core.ai import generate_tests
from lunar.core.discovery import discover_schema
from lunar.utils.config import load_config
from lunar.utils.printer import success, error, warn, info, print_panel, CYAN, MAGENTA, RESET, BOLD, GRAY


def normalize_tests(tests):

    # If AI returned a JSON string
    if isinstance(tests, str):
        try:
            tests = json.loads(tests)
        except Exception:
            print("✖ AI returned invalid JSON")
            return []

    # If AI wrapped tests inside an object
    if isinstance(tests, dict):

        # Common wrapper keys
        for key in ["tests", "test_cases", "cases", "data"]:
            if key in tests and isinstance(tests[key], list):
                return tests[key]

        # First list found in dict
        for value in tests.values():
            if isinstance(value, list):
                return value

        return []

    # Already a list
    if isinstance(tests, list):
        return tests

    return []


def run(args):

    if len(args) == 0:
        error("Usage: lunar gen <endpoint> [METHOD]")
        return

    endpoint = args[0]
    method = args[1].upper() if len(args) > 1 else None

    config = load_config()
    if not config:
        error("Run lunar init first")
        return

    # Use default GET method for endpoint schema discovery
    discovery_method = method if method and method != "CRUD" else "GET"
    info(f"Initiating schema discovery for {CYAN}{BOLD}{endpoint}{RESET} via {discovery_method}...")

    schema = discover_schema(
        config["base_url"],
        endpoint,
        discovery_method
    )

    schema_lines = [
        f"{CYAN}{BOLD}Status Code:{RESET} {schema.get('status_code')}",
        f"{CYAN}{BOLD}Response Type:{RESET} {schema.get('type')}",
        f"{CYAN}{BOLD}Schema Keys:{RESET} {', '.join(schema.get('keys', [])) or 'None'}",
    ]
    print_panel("ENDPOINT SCHEMA DISCOVERED", schema_lines, border_color=CYAN)

    agent_desc = f"{method} constraints" if method else "full CRUD lifecycle"
    info(f"Invoking AI agent ({MAGENTA}Qwen-2.5-Coder{RESET}) to generate test cases targeting {agent_desc}...")

    raw_tests = generate_tests(
        endpoint,
        method,
        schema
    )

    tests = normalize_tests(raw_tests)

    if not tests:
        error("No valid test scenarios generated by AI agent.")
        if raw_tests:
            print(f"\n{GRAY}Raw Agent Output:{RESET}\n{raw_tests}")
        return

    os.makedirs("lunar_tests", exist_ok=True)

    filename = endpoint.strip("/")

    if not filename:
        filename = "root"

    filepath = f"lunar_tests/{filename}.json"

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(
            tests,
            f,
            indent=4
        )

    print(f"\n{MAGENTA}{BOLD}GENERATED TEST CASES SUMMARY{RESET}\n")

    for test in tests:
        if not isinstance(test, dict):
            warn(f"Skipping invalid test structure: {test}")
            continue

        test_details = [
            f"{CYAN}Route:{RESET}      {test.get('method', 'GET')} {test.get('endpoint', endpoint)}",
        ]

        # Display payload body if present
        body = test.get("body")
        if body:
            test_details.append(f"{CYAN}Payload:{RESET}    {json.dumps(body)}")

        # Display custom headers if present
        headers = test.get("headers")
        if headers:
            test_details.append(f"{CYAN}Headers:{RESET}    {json.dumps(headers)}")

        # Display query parameters if present
        query_params = test.get("query_params")
        if query_params:
            test_details.append(f"{CYAN}Params:{RESET}     {json.dumps(query_params)}")

        # Print all assertions in detail
        assertions = test.get("assertions", {})
        assertions_str = f"Status: {assertions.get('status_code')}"
        if "content_type" in assertions:
            assertions_str += f", Content-Type: {assertions.get('content_type')}"
        if "contains_text" in assertions:
            assertions_str += f", Contains: {assertions.get('contains_text')}"
        if "json_keys" in assertions:
            assertions_str += f", Keys: {assertions.get('json_keys')}"
        if "json_types" in assertions:
            assertions_str += f", Types: {assertions.get('json_types')}"
        if "json_values" in assertions:
            assertions_str += f", Values: {assertions.get('json_values')}"
        if "max_response_time_ms" in assertions:
            assertions_str += f", MaxTime: {assertions.get('max_response_time_ms')}ms"

        test_details.append(f"{CYAN}Assertions:{RESET} {assertions_str}")

        print_panel(f"TEST: {test.get('name', 'Unnamed Test')}", test_details, border_color=MAGENTA)

    success(f"Generated test suite successfully compiled and saved to {CYAN}{filepath}{RESET}!")